### ISSUE TITLE
Small typo in example

### ISSUE THREAD

**Issue by scls19fr** [PaulStoffregen/FreqMeasure#12]
Hello,

on
https://www.pjrc.com/teensy/td_libs_FreqMeasure.html
I noticed a small typo in example

    float frequency FreqMeasure.countToFrequency(sum / count);

should be

    float frequency = FreqMeasure.countToFrequency(sum / count);

Kind regard

**Comment by PaulStoffregen** [comment]
Thanks.  Fixed.
