### ISSUE TITLE
fix commented config's

### ISSUE THREAD

**Issue by manitou48** [PaulStoffregen/FreqMeasure#13]
In util//FreqMeasureCapture.h  for T.36/3.5, need to change commented  FTM2 pin number configs to
#define CAPTURE_USE_FTM2_CH0 29
#define CAPTURE_USE_FTM2_CH1 30
Original pins  are OK for T3.0/3.1/3.2

discussions https://forum.pjrc.com/threads/45530-Teensy-3-6-FreqMeasure-alternate-pins

**Comment by PaulStoffregen** [comment]
Thanks!  :)
