### ISSUE TITLE
Configuration for Seeedunio GPRS (based on Leonardo) is difficult

### ISSUE THREAD

**Issue by cdmein** [PaulStoffregen/FreqMeasure#7]
Hi

Thanks for the work on the library. I managed to get this working first time on an Arduino Mega and an Uno.

When I tried to get this running on a Seeeduino GPRS I had issues. I got it working by trial and error but I wondered whether you would consider updating the README and possibly changing how the FreqMeasureCapture.h is defined for this board.

FreqMeasure worked on TIMER1 on PIN 5 in the end.

In FreqMeasureCapture.h the Seeeduino is 'defined' as a "__AVR_ATmega32U4__". That define block (line 51) defines TIMER3 and suggests pin 10. Your readme file suggestes pin 13. This does not work.

The Seeeduino GPRS sends data really seamlessly so I think it might become quite popular. Hopefully updating the documentation a little might help people out.

Thanks

Chris

**Comment by PaulStoffregen** [comment]
I've updated the web page, with a link to this issue.  Hopefully anyone needing to use this board will see it.
