### ISSUE TITLE
Does not support Arduino Micro

### ISSUE THREAD

**Issue by smd75jr** [PaulStoffregen/FreqMeasure#8]
The library does not appear to support the Arduino Micro, or if it does, it is not clear what pins to use.

**Comment by PaulStoffregen** [comment]
The required signals are here:

https://github.com/PaulStoffregen/FreqMeasure/blob/master/util/FreqMeasureCapture.h#L51

Maybe you could find the schematic and tell me which pins those are on?  (no, I don't have this board and I'm not planning to get one for testing.... this is how open source works, things get supported when people contribute such details)

**Comment by smd75jr** [comment]
I was looking at that but I have no experience with library programming at all. After annother look accoding to the schematics ([here](https://www.arduino.cc/en/uploads/Main/arduino-micro-schematic.pdf)), it appears that ICP1 is on Digital Pin 4 and ICP3 is on Digital Pin 13.

Thanks,
smd75jr

**Comment by PaulStoffregen** [comment]
Good.  Please let me know when you've tested and confirmed it works on the actual hardware.  Then I'll update the docs.

**Comment by smd75jr** [comment]
I can confirm that it does indeed work using the example sketch on pin 13.

Thanks,
smd75jr
